/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fqcheng220_ffmpegdemo_TestActivity */

#ifndef _Included_com_fqcheng220_ffmpegdemo_TestActivity
#define _Included_com_fqcheng220_ffmpegdemo_TestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fqcheng220_ffmpegdemo_TestActivity
 * Method:    testNativeMethod1
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fqcheng220_ffmpegdemo_TestActivity_testNativeMethod1
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
