/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fqcheng220_ffmpegdemo_MainActivity */

#ifndef _Included_com_fqcheng220_ffmpegdemo_MainActivity
#define _Included_com_fqcheng220_ffmpegdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fqcheng220_ffmpegdemo_MainActivity
 * Method:    stream
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fqcheng220_ffmpegdemo_MainActivity_stream
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
